Repository plotly/plotly.py, pull requests merged in 2024-11, with the labels that each got.

#4822 Drop notebook 6
  .circleci/config.yml
  README.md
  contributing.md
  doc/python/getting-started.md
  doc/python/troubleshooting.md
  packages/javascript/jupyterlab-plotly/README.md
  packages/javascript/jupyterlab-plotly/package-lock.json
  packages/javascript/jupyterlab-plotly/package.json
  packages/javascript/jupyterlab-plotly/src/Figure.ts
  packages/javascript/jupyterlab-plotly/src/extension.ts
  packages/javascript/jupyterlab-plotly/src/index.ts
  packages/javascript/jupyterlab-plotly/src/jupyterlab-plugin.ts
  packages/javascript/jupyterlab-plotly/src/lib.d.ts
  packages/javascript/jupyterlab-plotly/src/plotly-renderer.ts
  packages/javascript/jupyterlab-plotly/src/version.ts
  packages/javascript/jupyterlab-plotly/style/index.css
  packages/javascript/jupyterlab-plotly/style/plotly.svg
  packages/javascript/jupyterlab-plotly/tsconfig.json
  packages/javascript/jupyterlab-plotly/webpack.config.js
  packages/python/plotly/MANIFEST.in
  packages/python/plotly/js/widget.ts
  packages/python/plotly/jupyterlab-plotly.json
  packages/python/plotly/jupyterlab_plotly/__init__.py
  packages/python/plotly/jupyterlab_plotly/nbextension/extension.js
  packages/python/plotly/plotly/io/_renderers.py
  packages/python/plotly/setup.py
  release.md
Labels: feature, P1

#4795 Fix typo in `ml-pca.md`
  doc/python/ml-pca.md
Labels: P1, community, fix

#4850 Update docs examples to use `title.text` instead of title as a string for `title`
  doc/python/3d-axes.md
  doc/python/3d-bubble-charts.md
  doc/python/3d-camera-controls.md
  doc/python/3d-mesh.md
  doc/python/3d-surface-plots.md
  doc/python/animations.md
  doc/python/axes.md
  doc/python/bar-charts.md
  doc/python/box-plots.md
  doc/python/bubble-charts.md
  doc/python/candlestick-charts.md
  doc/python/choropleth-maps.md
  doc/python/colorscales.md
  doc/python/continuous-error-bars.md
  doc/python/contour-plots.md
  doc/python/county-choropleth.md
  doc/python/datashader.md
  doc/python/dot-plots.md
  doc/python/dumbbell-plots.md
  doc/python/figure-labels.md
  doc/python/figurewidget.md
  doc/python/heatmaps.md
  doc/python/horizontal-bar-charts.md
  doc/python/hover-text-and-formatting.md
  doc/python/legend.md
  doc/python/line-and-scatter.md
  doc/python/line-charts.md
  doc/python/marker-style.md
  doc/python/ml-knn.md
  doc/python/ml-regression.md
  doc/python/ml-roc-pr.md
  doc/python/multiple-axes.md
  doc/python/ohlc-charts.md
  doc/python/plot-data-from-csv.md
  doc/python/sankey-diagram.md
  doc/python/scatter-plots-on-maps.md
  doc/python/shapes.md
  doc/python/splom.md
  doc/python/templates.md
  doc/python/ternary-contour.md
  doc/python/tile-scatter-maps.md
  doc/python/trisurf.md
  doc/python/wind-rose-charts.md
Labels: P1, documentation

#4862 Add redirect for maplibre link
  doc/python/migrate-to-maplibre.md
Labels: P1, fix, documentation

#4823 Switch to use anywidget
  .circleci/config.yml
  .gitignore
  README.md
  contributing.md
  doc/python/getting-started.md
  doc/python/troubleshooting.md
  doc/requirements.txt
  packages/javascript/jupyterlab-plotly/README.md
  packages/javascript/jupyterlab-plotly/package-lock.json
  packages/javascript/jupyterlab-plotly/package.json
  packages/javascript/jupyterlab-plotly/src/extension.ts
  packages/javascript/jupyterlab-plotly/src/index.ts
  packages/javascript/jupyterlab-plotly/src/jupyterlab-plugin.ts
  packages/javascript/jupyterlab-plotly/src/lib.d.ts
  packages/javascript/jupyterlab-plotly/src/plotly-renderer.ts
  packages/javascript/jupyterlab-plotly/src/version.ts
  packages/javascript/jupyterlab-plotly/style/index.css
  packages/javascript/jupyterlab-plotly/style/plotly.svg
  packages/javascript/jupyterlab-plotly/tsconfig.json
  packages/javascript/jupyterlab-plotly/webpack.config.js
  packages/python/chart-studio/test_requirements/requirements_37.txt
  packages/python/plotly/MANIFEST.in
  packages/python/plotly/codegen/__init__.py
  packages/python/plotly/js/package-lock.json
  packages/python/plotly/js/package.json
  packages/python/plotly/js/tsconfig.json
  packages/python/plotly/js/widget.ts
  packages/python/plotly/jupyterlab-plotly.json
  packages/python/plotly/jupyterlab_plotly/__init__.py
  packages/python/plotly/jupyterlab_plotly/nbextension/extension.js
  packages/python/plotly/plotly/basewidget.py
  packages/python/plotly/plotly/graph_objects/__init__.py
  packages/python/plotly/plotly/graph_objs/__init__.py
  packages/python/plotly/plotly/io/_renderers.py
  packages/python/plotly/plotly/missing_anywidget.py
  packages/python/plotly/plotly/missing_ipywidgets.py
  packages/python/plotly/plotly/tests/test_core/test_figure_widget_backend/test_missing_anywidget.py
  packages/python/plotly/plotly/tests/test_core/test_figure_widget_backend/test_missing_ipywigets.py
  packages/python/plotly/setup.py
  packages/python/plotly/test_requirements/requirements_310_optional.txt
  packages/python/plotly/test_requirements/requirements_311_optional.txt
  packages/python/plotly/test_requirements/requirements_312_no_numpy_optional.txt
  packages/python/plotly/test_requirements/requirements_312_np2_optional.txt
  packages/python/plotly/test_requirements/requirements_312_optional.txt
  packages/python/plotly/test_requirements/requirements_38_optional.txt
  packages/python/plotly/test_requirements/requirements_39_optional.txt
  packages/python/plotly/test_requirements/requirements_39_pandas_2_optional.txt
  release.md
Labels: feature, P1, community

#4790 feat: make plotly-express dataframe agnostic via narwhals
  CHANGELOG.md
  packages/python/plotly/_plotly_utils/basevalidators.py
  packages/python/plotly/_plotly_utils/tests/validators/test_pandas_series_input.py
  packages/python/plotly/optional-requirements.txt
  packages/python/plotly/plotly/data/__init__.py
  packages/python/plotly/plotly/express/__init__.py
  packages/python/plotly/plotly/express/_core.py
  packages/python/plotly/plotly/express/_doc.py
  packages/python/plotly/plotly/express/_imshow.py
  packages/python/plotly/plotly/express/trendline_functions/__init__.py
  packages/python/plotly/plotly/figure_factory/_hexbin_mapbox.py
  packages/python/plotly/plotly/tests/test_optional/test_figure_factory/test_figure_factory.py
  packages/python/plotly/plotly/tests/test_optional/test_px/conftest.py
  packages/python/plotly/plotly/tests/test_optional/test_px/test_facets.py
  packages/python/plotly/plotly/tests/test_optional/test_px/test_marginals.py
  packages/python/plotly/plotly/tests/test_optional/test_px/test_px.py
  packages/python/plotly/plotly/tests/test_optional/test_px/test_px_functions.py
  packages/python/plotly/plotly/tests/test_optional/test_px/test_px_hover.py
  packages/python/plotly/plotly/tests/test_optional/test_px/test_px_input.py
  packages/python/plotly/plotly/tests/test_optional/test_px/test_px_wide.py
  packages/python/plotly/plotly/tests/test_optional/test_px/test_trendline.py
  packages/python/plotly/plotly/tests/test_optional/test_tools/test_figure_factory.py
  packages/python/plotly/plotly/tests/test_optional/test_utils/test_utils.py
  packages/python/plotly/requirements.txt
  packages/python/plotly/setup.py
  packages/python/plotly/test_requirements/requirements_310_core.txt
  packages/python/plotly/test_requirements/requirements_310_optional.txt
  packages/python/plotly/test_requirements/requirements_311_core.txt
  packages/python/plotly/test_requirements/requirements_311_optional.txt
  packages/python/plotly/test_requirements/requirements_312_core.txt
  packages/python/plotly/test_requirements/requirements_312_no_numpy_optional.txt
  packages/python/plotly/test_requirements/requirements_312_np2_optional.txt
  packages/python/plotly/test_requirements/requirements_312_optional.txt
  packages/python/plotly/test_requirements/requirements_38_core.txt
  packages/python/plotly/test_requirements/requirements_38_optional.txt
  packages/python/plotly/test_requirements/requirements_39_core.txt
  packages/python/plotly/test_requirements/requirements_39_optional.txt
  packages/python/plotly/test_requirements/requirements_39_pandas_2_optional.txt
Labels: feature, P1, community

#4865 Do not assign `offsetgroup` to traces in px unless `barmode="group"`
  packages/python/plotly/plotly/express/_core.py
Labels: P1, fix

#4644 Add plotly[express] extra for easily installing Plotly Express dependencies
  CHANGELOG.md
  contributing.md
  packages/python/plotly/MANIFEST.in
  packages/python/plotly/optional-requirements.txt
  packages/python/plotly/plotly/express/__init__.py
  packages/python/plotly/requires-express.txt
  packages/python/plotly/requires-install.txt
  packages/python/plotly/requires-optional.txt
  packages/python/plotly/setup.py
Labels: feature, P2, infrastructure

#4878 fix: Avoid using iter_rows in _check_dataframe_all_leaves to enable cuDF input
  packages/python/plotly/plotly/express/_core.py
Labels: P1, community, fix

#4881 Modify template generator to automatically add new `map` traces and subplots
  packages/python/plotly/plotly/package_data/templates/ggplot2.json
  packages/python/plotly/plotly/package_data/templates/plotly.json
  packages/python/plotly/plotly/package_data/templates/plotly_dark.json
  packages/python/plotly/plotly/package_data/templates/plotly_white.json
  packages/python/plotly/plotly/package_data/templates/seaborn.json
  packages/python/plotly/plotly/package_data/templates/simple_white.json
  packages/python/plotly/templategen/__init__.py
  packages/python/plotly/templategen/__main__.py
  packages/python/plotly/templategen/utils/__init__.py
Labels: P1, fix

#4902 test: Pass native dataframe in `test_pass_df_columns` and `test_category_order_with_category_as_x`
  packages/python/plotly/plotly/tests/test_optional/test_px/test_px.py
  packages/python/plotly/plotly/tests/test_optional/test_px/test_px_input.py
Labels: community, fix

#4840 Docs updates for Plotly.py version 6
  CHANGELOG.md
  README.md
  doc/python/LaTeX.md
  doc/python/aggregations.md
  doc/python/bar-charts.md
  doc/python/datashader.md
  doc/python/filter.md
  doc/python/getting-started.md
  doc/python/group-by.md
  doc/python/heatmaps.md
  doc/python/multiple-transforms.md
  doc/python/performance.md
  doc/python/px-arguments.md
  doc/python/smith-charts.md
  doc/python/v4-migration.md
  doc/python/v6-changes.md
  doc/python/webgl-vs-svg.md
  doc/unconverted/python/chord-diagram.md
  doc/unconverted/python/filled-chord-diagram.md
Labels: feature, P1, documentation
