Repository plotly/plotly.py, pull requests merged in 2024-09, with the labels that each got.

#4744 Update file names to remove mapbox
  doc/python/density-heatmaps.md
  doc/python/filled-area-tile-maps.md
  doc/python/lines-on-tile-maps.md
  doc/python/tile-county-choropleth.md
  doc/python/tile-map-layers.md
  doc/python/tile-scatter-maps.md
Labels: P2, fix

#3628 Smoothing being applied in the "unnoised" data
  doc/python/smoothing.md
Labels: P2, fix

#4758 Version changes for v5.24.1
  CHANGELOG.md
  README.md
  packages/javascript/jupyterlab-plotly/package-lock.json
  packages/javascript/jupyterlab-plotly/package.json
  packages/python/plotly/plotly/_widget_version.py
Labels: feature, P2

#3793 Fix "Update Button" example in Python custom buttons doc page
  doc/python/custom-buttons.md
Labels: P2, community, fix

#4147 Align an annotation with the center of a donut pie
  doc/python/pie-charts.md
Labels: P2, community, documentation

#4606 Clarify Jupyterlab install
  doc/python/getting-started.md
Labels: feature, P3, documentation

#4063 Update ml-roc-pr.md
  doc/python/ml-roc-pr.md
Labels: P2, community, fix, documentation

#4661 remove out of date information on static image rendering
  doc/python/renderers.md
Labels: P2, community, fix, documentation

#4044 make moving-point-on-a-curve faster
  doc/python/animations.md
Labels: feature, P2, community

#4647 Add v1hovermode to the list of all the modebar options
  doc/python/configuration-options.md
Labels: P2, community, fix

#4764 Update LICENSE.txt
  LICENSE.txt
Labels: P1, community, fix

#4747 Update _chart_types.py vertices docstrings to 'a vertex'
  packages/python/plotly/plotly/express/_chart_types.py
Labels: P3, community, fix, documentation

#4282 Update box-plots.md
  doc/python/box-plots.md
Labels: feature, P2, community, documentation

#4743 Update percy tests to use maps
  test/percy/plotly-express.py
Labels: P2, fix
