Repository plotly/plotly.py, pull requests merged in 2024-08, with the labels that each got.

#4728 Fix CI failure
  .circleci/config.yml
Labels: P1, fix, infrastructure

#3363 Fix typo in gapminder-example.md
  doc/unconverted/python/gapminder-example.md
Labels: P2, community, fix, documentation

#4706 Updates for maplibre maps
  doc/apidoc/plotly.express.rst
  doc/python/axes.md
  doc/python/bubble-maps.md
  doc/python/choropleth-maps.md
  doc/python/county-choropleth.md
  doc/python/datashader.md
  doc/python/figure-structure.md
  doc/python/filled-area-on-mapbox.md
  doc/python/heatmaps.md
  doc/python/hexbin-mapbox.md
  doc/python/hover-text-and-formatting.md
  doc/python/line-charts.md
  doc/python/lines-on-mapbox.md
  doc/python/lines-on-maps.md
  doc/python/map-configuration.md
  doc/python/mapbox-county-choropleth.md
  doc/python/mapbox-density-heatmaps.md
  doc/python/mapbox-layers.md
  doc/python/migrate-to-maplibre.md
  doc/python/plotly-express.md
  doc/python/scatter-plots-on-maps.md
  doc/python/scattermapbox.md
  doc/unconverted/python/tesla-supercharging-stations.md
  packages/python/plotly/plotly/_subplots.py
  packages/python/plotly/plotly/express/__init__.py
  packages/python/plotly/plotly/express/_chart_types.py
  packages/python/plotly/plotly/express/_core.py
  packages/python/plotly/plotly/express/_doc.py
  packages/python/plotly/plotly/subplots.py
  packages/python/plotly/templategen/utils/__init__.py
Labels: feature, P1, documentation

#4727 Add tests for the keys that should be skipped in base64 conversion
  packages/python/plotly/_plotly_utils/basevalidators.py
  packages/python/plotly/plotly/tests/test_optional/test_graph_objs/test_skipped_b64_keys.py
Labels: feature, P1, testing
