Repository plotly/plotly.py, pull requests merged in 2024-10, with the labels that each got.

#3746 Remove errroneous comma in SVG path
  doc/python/shapes.md
Labels: P2, fix

#4770 updating year(s) in license
  LICENSE.txt
Labels: P2, fix, documentation

#4658 fix typo in error message formatting in process_args_into_dataframe
  packages/python/plotly/plotly/express/_core.py
Labels: P2, community, fix, documentation

#3891 fix SyntaxWarning for comparing with a literal
  packages/python/chart-studio/chart_studio/tools.py
Labels: P2, community, fix

#4781 fixing a bug that causes the hovertext to show %{text} rather than th…
  doc/python/hover-text-and-formatting.md
Labels: P2, community, fix

#4784 Convert base64 in BaseFigure.to_dict instead of validate_coerce
  packages/python/plotly/_plotly_utils/basevalidators.py
  packages/python/plotly/_plotly_utils/utils.py
  packages/python/plotly/plotly/basedatatypes.py
  packages/python/plotly/plotly/io/_utils.py
Labels: feature, P1

#4793 Remove deprecated attributes from docs
  doc/python/3d-bubble-charts.md
  doc/python/bar-charts.md
  doc/python/carpet-contour.md
  doc/python/colorscales.md
  doc/python/contour-plots.md
  doc/python/multiple-axes.md
  doc/python/network-graphs.md
  doc/python/range-slider.md
  doc/python/scatter-plots-on-maps.md
  doc/python/setting-graph-size.md
  doc/python/ternary-plots.md
  doc/unconverted/python/cars-exploration.md
Labels: P1, fix

#4804 Update jupytext version to latest
  doc/requirements.txt
Labels: P1, fix

#4470 Use plotly.js `base64` API to store and pass typed arrays declared by numpy, pandas, etc.
  CHANGELOG.md
  packages/python/plotly/_plotly_utils/utils.py
  packages/python/plotly/plotly/basedatatypes.py
  packages/python/plotly/plotly/tests/test_optional/test_graph_objs/test_skipped_b64_keys.py
  packages/python/plotly/plotly/tests/test_optional/test_px/test_px_functions.py
  packages/python/plotly/plotly/tests/test_optional/test_utils/test_utils.py
Labels: feature, P1

#4763 Use modern `native ES6 import` to load plotly.js bundle instead of `requirejs` which is no longer under active development
  CHANGELOG.md
  packages/python/plotly/plotly/basedatatypes.py
  packages/python/plotly/plotly/io/_base_renderers.py
  packages/python/plotly/plotly/io/_html.py
  packages/python/plotly/plotly/tests/test_io/test_renderers.py
Labels: feature, P1, dependencies

#4812 Remove `autotick`
  doc/unconverted/python/amazon-redshift.md
  doc/unconverted/python/google_big_query.md
Labels: P1, fix

#4816 Merge changes from doc-prod to master
  doc/python/3d-bubble-charts.md
  doc/python/animations.md
  doc/python/bar-charts.md
  doc/python/box-plots.md
  doc/python/carpet-contour.md
  doc/python/colorscales.md
  doc/python/configuration-options.md
  doc/python/contour-plots.md
  doc/python/custom-buttons.md
  doc/python/getting-started.md
  doc/python/hover-text-and-formatting.md
  doc/python/ml-roc-pr.md
  doc/python/multiple-axes.md
  doc/python/network-graphs.md
  doc/python/pie-charts.md
  doc/python/range-slider.md
  doc/python/scatter-plots-on-maps.md
  doc/python/setting-graph-size.md
  doc/python/shapes.md
  doc/python/ternary-plots.md
  doc/unconverted/python/cars-exploration.md
Labels: feature, P1, fix

#4831 Remove tenacity dependency
  CHANGELOG.md
  environment.yml
  packages/python/plotly/plotly/io/_orca.py
  packages/python/plotly/recipe/meta.yaml
  packages/python/plotly/requirements.txt
  packages/python/plotly/setup.py
  packages/python/plotly/test_requirements/requirements_310_core.txt
  packages/python/plotly/test_requirements/requirements_310_optional.txt
  packages/python/plotly/test_requirements/requirements_311_core.txt
  packages/python/plotly/test_requirements/requirements_311_optional.txt
  packages/python/plotly/test_requirements/requirements_312_core.txt
  packages/python/plotly/test_requirements/requirements_312_no_numpy_optional.txt
  packages/python/plotly/test_requirements/requirements_312_optional.txt
  packages/python/plotly/test_requirements/requirements_38_core.txt
  packages/python/plotly/test_requirements/requirements_38_optional.txt
  packages/python/plotly/test_requirements/requirements_39_core.txt
  packages/python/plotly/test_requirements/requirements_39_optional.txt
  packages/python/plotly/test_requirements/requirements_39_pandas_2_optional.txt
Labels: feature, P1, dependencies

#4835 Remove old content
  doc/python/animations.md
  doc/python/visualizing-mri-volume-slices.md
Labels: feature, P1, documentation

#4830 Add subtitle attribute to Plotly Express figures
  CHANGELOG.md
  packages/python/plotly/plotly/express/_chart_types.py
  packages/python/plotly/plotly/express/_core.py
  packages/python/plotly/plotly/express/_doc.py
Labels: feature, P2
