Repository plotly/plotly.py, pull requests merged in 2024-12, with the labels that each got.

#4922 fix: Skip base64 conversion for empty arrays (fixes #4919)
  packages/python/plotly/_plotly_utils/utils.py
  packages/python/plotly/plotly/tests/test_io/test_to_from_json.py
  packages/python/plotly/plotly/tests/test_optional/test_px/test_px.py
Labels: P1, fix

#4921 fix: pandas DataFrame with non-default Index was resulting in scrambled data in scatter_matrix
  packages/python/plotly/plotly/express/_core.py
  packages/python/plotly/plotly/tests/test_optional/test_px/test_px_input.py
  packages/python/plotly/requires-install.txt
  packages/python/plotly/test_requirements/requirements_310_core.txt
  packages/python/plotly/test_requirements/requirements_310_optional.txt
  packages/python/plotly/test_requirements/requirements_311_core.txt
  packages/python/plotly/test_requirements/requirements_311_optional.txt
  packages/python/plotly/test_requirements/requirements_312_core.txt
  packages/python/plotly/test_requirements/requirements_312_no_numpy_optional.txt
  packages/python/plotly/test_requirements/requirements_312_np2_optional.txt
  packages/python/plotly/test_requirements/requirements_312_optional.txt
  packages/python/plotly/test_requirements/requirements_38_core.txt
  packages/python/plotly/test_requirements/requirements_38_optional.txt
  packages/python/plotly/test_requirements/requirements_39_core.txt
  packages/python/plotly/test_requirements/requirements_39_optional.txt
  packages/python/plotly/test_requirements/requirements_39_pandas_2_optional.txt
Labels: community, fix

#4914 fix: px.timeline was raising when x_start and/or x_end were already datetime for Polars / PyArrow
  packages/python/plotly/plotly/express/_core.py
  packages/python/plotly/plotly/tests/test_optional/test_px/test_px_functions.py
Labels: P2, community, fix

#4916 fix: add narwhals to conda recipe
  packages/python/plotly/recipe/meta.yaml
Labels: community, fix, infrastructure

#4926 patch: deepcopy figure fix
  packages/python/plotly/_plotly_utils/basevalidators.py
  packages/python/plotly/_plotly_utils/tests/validators/test_fig_deepcopy.py
Labels: P1, community, fix

#4937 Bump cache version to fix failing doc build
  .circleci/config.yml
Labels: P1, fix, dependencies

#4886 adding a JavaScript/Jinja example to dropdowns.md
  doc/python/dropdowns.md
Labels: feature, P2, community, documentation
