Repository plotly/plotly.py, pull requests merged in 2025-10, with the labels that each got.

#5315 fix a typo in `_ternary_contour.py`
  plotly/figure_factory/_ternary_contour.py
Labels: P1, community, fix

#5312 Use native legends when converting from matplotlib
  plotly/matplotlylib/renderer.py
  plotly/matplotlylib/tests/__init__.py
  plotly/matplotlylib/tests/test_renderer.py
Labels: P1, community, fix

#5258 Fix issue with default renderer when `ipython` is installed
  plotly/io/_renderers.py
  tests/test_io/test_renderers.py
Labels: P1, fix

#5180 Allow `shared_yaxes` to work with secondary axes
  plotly/_subplots.py
  tests/test_core/test_subplots/test_make_subplots.py
Labels: feature, P1, community
