Repository plotly/plotly.py, pull requests merged in 2025-03, with the labels that each got.

#4873 Adding an example of source lines or notes on the bottom of graphs
  doc/python/text-and-annotations.md
Labels: P1, community, fix, documentation

#5019 Unpin test requirements
  .circleci/config.yml
  plotly/tools.py
  test_requirements/requirements_310_core.txt
  test_requirements/requirements_310_optional.txt
  test_requirements/requirements_311_core.txt
  test_requirements/requirements_311_optional.txt
  test_requirements/requirements_312_core.txt
  test_requirements/requirements_312_no_numpy_optional.txt
  test_requirements/requirements_312_np2_optional.txt
  test_requirements/requirements_312_optional.txt
  test_requirements/requirements_38_core.txt
  test_requirements/requirements_38_optional.txt
  test_requirements/requirements_39_core.txt
  test_requirements/requirements_39_optional.txt
  test_requirements/requirements_39_pandas_2_optional.txt
  test_requirements/requirements_core.txt
  test_requirements/requirements_optional.txt
  tests/test_optional/test_px/test_px_input.py
Labels: feature, P1, dependencies

#5094 Remove unused step
  RELEASE.md
Labels: P1, documentation

#5104 Add handling for if jupyterlab / notebook isn't defined
  plotly/io/_renderers.py
Labels: P1, fix

#5102 Fix widget initialization issue in v6
  CHANGELOG.md
  plotly/basewidget.py
  tests/test_core/test_figure_widget_backend/test_validate_initialization.py
Labels: P1, community, fix

#5052 Add initial test pypi release workflow
  .github/workflows/test-release.yml
Labels: P1, testing
