Repository plotly/plotly.py, pull requests merged in 2025-06, with the labels that each got.

#5201 switched from hex codes to CSS colors
  doc/python/dropdowns.md
Labels: P1, community, fix

#5207 Support setting plotly.js path for Kaleido v1 image export
  plotly/io/_defaults.py
  plotly/io/_kaleido.py
  pyproject.toml
  test_requirements/requirements_optional.txt
  tests/test_optional/test_kaleido/test_kaleido.py
Labels: P1, fix

#4958 Add Pictogram Bar Chart Tested and Improvements
  doc/python/bar-charts.md
Labels: feature, P2, community

#5237 Version updates for 6.2.0
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: P1, infrastructure

#5243 Merge doc prod changes to main
  doc/apidoc/conf.py
  doc/python/static-image-export.md
  doc/requirements.txt
Labels: P1, documentation
