Repository plotly/plotly.py, pull requests merged in 2025-07, with the labels that each got.

#5270 Add how to set plotly.js
  doc/python/static-image-export.md
Labels: P1, documentation

#5290 preload _plotly_utils to display full reference content for plotly.colors
  mkdocs.yml
Labels: mkdocs

#5299 fix: add missing arguments to commands.py
  commands.py
Labels: P1, fix, infrastructure
