Repository plotly/plotly.py, pull requests merged in 2025-04, with the labels that each got.

#5126 Remove deprecated append_trace
  doc/python/3d-axes.md
  doc/python/histograms.md
  doc/python/horizontal-bar-charts.md
  doc/python/subplots.md
  plotly/subplots.py
  plotly/tools.py
Labels: documentation

#5134 Update print_grid default
  plotly/subplots.py
Labels: P1, documentation

#5135 Fix return type
  plotly/io/_html.py
Labels: fix, documentation

#5140 corrected a label from Canada to Oceania
  doc/python/bar-charts.md
Labels: P1, community, fix, documentation

#5137 Add supported CSS colors page
  doc/python/supported-colors.md
Labels: P1, documentation

#4994 adding a diverging bar example to the horizontal bar documentation
  doc/python/horizontal-bar-charts.md
Labels: P2, community, documentation

#5148 Applying changes that #4994 made to "main" to "doc-prod"
  doc/python/horizontal-bar-charts.md
Labels: P1, documentation

#5062 Support Kaleido v1 in Plotly.py
  .circleci/config.yml
  CHANGELOG.md
  plotly/basedatatypes.py
  plotly/io/__init__.py
  plotly/io/_defaults.py
  plotly/io/_kaleido.py
  plotly/io/_utils.py
  plotly/io/kaleido.py
  pyproject.toml
  test_requirements/requirements_optional.txt
  tests/test_optional/test_kaleido/test_kaleido.py
Labels: feature, P1
