Repository plotly/plotly.py, pull requests merged in 2025-02, with the labels that each got.

#5004 Add note on DDK compatibility
  doc/python/performance.md
  doc/python/v6-changes.md
Labels: P1, documentation

#4977 fix: cleaning up tests for release
  .circleci/config.yml
  _plotly_utils/tests/validators/test_enumerated_validator.py
  plotly/tests/test_core/test_subplots/test_make_subplots.py
  plotly/tests/test_io/test_to_from_plotly_json.py
  plotly/tests/test_optional/test_graph_objs/test_skipped_b64_keys.py
  plotly/tests/test_optional/test_px/test_px_hover.py
  plotly/tests/test_optional/test_px/test_px_input.py
  plotly/tests/test_orca/__init__.py
  plotly/tests/test_orca/images/darwin/fig1.eps
  plotly/tests/test_orca/images/darwin/latexfig.eps
  plotly/tests/test_orca/images/darwin/topofig.eps
  plotly/tests/test_orca/images/linux/fig1.eps
  plotly/tests/test_orca/images/linux/latexfig.eps
  plotly/tests/test_orca/images/linux/topofig.eps
  plotly/tests/test_orca/resources/2011_us_ag_exports.csv
  plotly/tests/test_orca/test_image_renderers.py
  plotly/tests/test_orca/test_orca_server.py
  plotly/tests/test_orca/test_sg_scraper.py
  plotly/tests/test_orca/test_to_image.py
  requires-optional.txt
  test_requirements/requirements_311_optional.txt
  test_requirements/requirements_312_optional.txt
Labels: P1, fix, testing

#5040 Fix TypeError: When using orjson and serializing pandas.NA
  CHANGELOG.md
  plotly/io/_json.py
  tests/test_io/test_to_from_plotly_json.py
Labels: P1, community, fix
